### PR TITLE
Finish implementation of pubsub

### LINKED ISSUE #115: Implementation of pubsub seems incorrect
The pubsub attribute in mockredis/client.py seems to be defined as a defaultdict that stores the lines passed by publish, whereas it should be a method that creates an object of PubSub(), that handles the subscription to the channel. We would still need that defaultdict under the cover and linked to the mocked PubSub instances that are handed out.

### PR DESCRIPTION
**Pull request by alertedsnake**
The original pubsub implementation didn't actually work
fully, it's supposed to be a callable.

So I've implemented much more of it, enough to mock reasonably.
You do basic things like publish messages, but most everything else
is just a no-op.  Most of what pubsub does doesn't really work well
when mocking anyway, so this is good enough to deal with the basics.

Feel free to suggest more functionality - I only need the basics,
but I'd be happy to do a bit more on this if needed.

Fixes #115

### CODE REVIEW

**Comment by gpip** [comment]
Hi, thanks for working on this. One feature of redis' publish is that it returns an integer representing the number of clients that received the message, do you see some way to integrate that into this?

**Comment by alertedsnake** [comment]
Hmm, it might be reasonable to return just '1' when testing since there's really no way to know the number of clients subscribed, but otherwise I'm not sure what you'd expect here.  I can see wanting the feature in the real publish method, but not why I'd be overly concerned about testing it.

**Comment by gpip** [comment]
There could be code that uses this return value from publish to do something different based on it. I think it would require implementing the subscribe piece on mockredis so I think it's out of scope for this PR.

**Comment by alertedsnake** [comment]
Ah yes, that's a good point, you'd need the subscribe feature first.

**Comment by alertedsnake** [comment]
Closing since this repo is no longer used.

**Pull request closed without merging**
